jobs:
  include:
    - stage: build server
      os: linux
      language: node_js
      node_js: 14
      script:
      - |
        yarn --cwd packages/comment/ build
        yarn --cwd packages/server build
        zip -r server-side.zip packages/comment/build packages/server/dist
    - stage: test
      script: echo test
