jobs:
  include:
    - stage: build server
      os: linux
      language: node_js
      node_js: 14
      script:
      - |
        echo node version
        echo $(node --version)
    - stage: test
      script: echo test
