jobs:
  include:
    - stage: build comment app
      os: linux
      dist: focal
      language: node_js
      node_js: 14
      script:
      - |
        yarn --cwd packages/comment/ build
        zip -r comment.zip packages/comment/build
      deploy:
        if branch = main AND type = push
        provider: release
        api_key: $GH_TOKEN
        file: comment.zip
        skip-cleanup: true
        draft: true
    - stage: build desktop app
      os: osx
      osx_image: xcode12
      language: node_js
      node_js: 14
      script:
      - |
        cd packages/desktop
        yarn --frozen-lockfile
        yarn build:screen
        yarn package:m
    -
      os: linux
      dist: focal
      services: docker
      language: generic
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      script:
      - |
        cd packages/desktop
        docker run --rm \
          -e ELECTRON_CACHE=$HOME/.cache/electron \
          -e ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder \
          -e CI=$CI \
          -e GH_TOKEN=$GH_TOKEN \
          -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
          -v ${PWD}:/project \
          -v $HOME/.cache/electron:/root/.cache/electron \
          -v $HOME/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "yarn install && yarn build:screen && yarn package:wl"

