name: Build and release comment app

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build comment app
        run: |
          yarn install
          yarn --cwd packages/comment build

      - name: Archive comment app
        uses: ihiroky/archive-action@v1
        with:
          file_path: build/comment.zip
          root_dir: packages/comment/build

      - name: Gets latest created release info
        id: latest_release_info
        uses: ihiroky/action-latest-release-info@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          echo draft:${{ steps.latest_release_info.outputs.draft }}
          echo upload_url:${{ steps.latest_release_info.outputs.upload_url }}
        shell: bash

      - name: Upload asset to github release if draft release exists.
        id: upload-release-asset
        if: ${{ steps.latest_release_info.outputs.draft == true }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: build/comment.zip
          asset_name: comment.zip
          asset_content_type: application/zip
