name: Build and release server-side apps

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build apps
        run: |
          yarn install
          yarn --cwd packages/comment build
          yarn --cwd packages/server  build

      - name: Create release directory tree
        run: |
          mkdir -p build/release
          cp -a packages/comment/build       build/release/comment
          mkdir -p build/release/server
          cp -a packages/server/dist         build/release/server
          cp -a packages/server/src/start.sh build/release/server
        shell: bash

      - name: Archive apps
        uses: ihiroky/archive-action@v1
        with:
          file_path: build/server-apps.zip
          root_dir: build/release/

      - name: Gets latest created release info
        id: latest_release_info
        uses: ihiroky/action-latest-release-info@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          echo draft:${{ steps.latest_release_info.outputs.draft }}
          echo upload_url:${{ steps.latest_release_info.outputs.upload_url }}
        shell: bash

      - name: Upload asset to github release if draft release exists.
        id: upload-release-asset
        if: ${{ steps.latest_release_info.outputs.draft == true }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: build/server-apps.zip
          asset_name: server-apps.zip
          asset_content_type: application/zip
