name: Build and release desktop app

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependent modules
        run: yarn install --frozen-lockfile --network-timeout 180000

      - name: Build apps
        run: |
          yarn --cwd packages/desktop/ build

      - name: Run tests
        run: |
          yarn jest packages/common/
          yarn jest packages/screen/
          yarn jest packages/poll/
          yarn jest --env jsdom packages/desktop/src/*/*.spec.ts
          yarn jest --env node packages/desktop/src/*.spec.ts

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          skip_build: true
          package_root: packages/desktop/
          args: -c electron-builder-config.json

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: live-comment-for-${{ matrix.os }}-${{ github.run_number }}
          path: packages/desktop/dist/live-comment*
